<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/stockadjustment/_show.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:36:06
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show StockAdjustment')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('stockadjustments.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$stockadjustment->id}}</td></tr>
		<tr><th>Product Id</th><td>{{$stockadjustment->product_id}}</td></tr>
		<tr><th>Adjustment Type Id</th><td>{{$stockadjustment->adjustment_type_id}}</td></tr>
		<tr><th>Quantity Adjusted</th><td>{{$stockadjustment->quantity_adjusted}}</td></tr>
		<tr><th>Reason</th><td>{{$stockadjustment->reason}}</td></tr>
		<tr><th>Adjusted By</th><td>{{$stockadjustment->adjusted_by}}</td></tr>
		<tr><th>Created At</th><td>{{$stockadjustment->created_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
