<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/wishlist/_index.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:37:30
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Wishlist')
@section('style')


@endsection
@section('page')
<a href="{{route('wishlists.create')}}">New Wishlist</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Customer Id</th>
			<th>Product Id</th>
			<th>Quantity</th>
			<th>Created At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($wishlists as $wishlist)
		<tr>
			<td>{{$wishlist->id}}</td>
			<td>{{$wishlist->customer_id}}</td>
			<td>{{$wishlist->product_id}}</td>
			<td>{{$wishlist->quantity}}</td>
			<td>{{$wishlist->created_at}}</td>

			<td>
			<form action = "{{route('wishlists.destroy',$wishlist->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('wishlists.show',$wishlist->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('wishlists.edit',$wishlist->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
