<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/wishlist/_show.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:37:30
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Wishlist')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('wishlists.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$wishlist->id}}</td></tr>
		<tr><th>Customer Id</th><td>{{$wishlist->customer_id}}</td></tr>
		<tr><th>Product Id</th><td>{{$wishlist->product_id}}</td></tr>
		<tr><th>Quantity</th><td>{{$wishlist->quantity}}</td></tr>
		<tr><th>Created At</th><td>{{$wishlist->created_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
