<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/order/_show.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:06:53
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Order')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('orders.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$order->id}}</td></tr>
		<tr><th>Customer Id</th><td>{{$order->customer_id}}</td></tr>
		<tr><th>Total Price</th><td>{{$order->total_price}}</td></tr>
		<tr><th>Order Status Id</th><td>{{$order->order_status_id}}</td></tr>
		<tr><th>Payment Status Id</th><td>{{$order->payment_status_id}}</td></tr>
		<tr><th>Created At</th><td>{{$order->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$order->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
