<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/promotionstatu/_index.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:33:41
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage PromotionStatu')
@section('style')


@endsection
@section('page')
<a href="{{route('promotionstatus.create')}}">New PromotionStatu</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Created At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($promotionstatus as $promotionstatu)
		<tr>
			<td>{{$promotionstatu->id}}</td>
			<td>{{$promotionstatu->name}}</td>
			<td>{{$promotionstatu->created_at}}</td>

			<td>
			<form action = "{{route('promotionstatus.destroy',$promotionstatu->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('promotionstatus.show',$promotionstatu->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('promotionstatus.edit',$promotionstatu->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
