<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/size/_index.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:35:29
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Size')
@section('style')


@endsection
@section('page')
<a href="{{route('sizes.create')}}">New Size</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Created At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($sizes as $size)
		<tr>
			<td>{{$size->id}}</td>
			<td>{{$size->name}}</td>
			<td>{{$size->created_at}}</td>

			<td>
			<form action = "{{route('sizes.destroy',$size->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('sizes.show',$size->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('sizes.edit',$size->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
