<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/size/_show.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:35:29
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Size')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('sizes.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$size->id}}</td></tr>
		<tr><th>Name</th><td>{{$size->name}}</td></tr>
		<tr><th>Created At</th><td>{{$size->created_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
