<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/promotion/_edit.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:33:15
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Promotion')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('promotions.index')}}">Manage</a>
<form action="{{route('promotions.update',$promotion)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="code" class="col-sm-2 col-form-label">Code</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="code" value="{{$promotion->code}}" id="code" placeholder="Code">
	</div>
</div>
<div class="row mb-3">
	<label for="discount_percentage" class="col-sm-2 col-form-label">Discount Percentage</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="discount_percentage" value="{{$promotion->discount_percentage}}" id="discount_percentage" placeholder="Discount Percentage">
	</div>
</div>
<div class="row mb-3">
	<label for="expiry_date" class="col-sm-2 col-form-label">Expiry Date</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="expiry_date" value="{{$promotion->expiry_date}}" id="expiry_date" placeholder="Expiry Date">
	</div>
</div>
<div class="row mb-3">
	<label for="promotion_status_id" class="col-sm-2 col-form-label">Promotion_Status</label>
	<div class="col-sm-10">
		<select class="form-control" name="promotion_status_id" id="promotion_status_id">
			@foreach($promotion_statuss as $promotion_status)
				@if($promotion_status->id==$promotion->promotion_status_id)
					<option value="{{$promotion_status->id}}" selected>{{$promotion_status->name}}</option>
				@else
					<option value="{{$promotion_status->id}}">{{$promotion_status->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
