<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/promotion/_index.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:33:15
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Promotion')
@section('style')


@endsection
@section('page')
<a href="{{route('promotions.create')}}">New Promotion</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Code</th>
			<th>Discount Percentage</th>
			<th>Expiry Date</th>
			<th>Promotion Status Id</th>
			<th>Created At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($promotions as $promotion)
		<tr>
			<td>{{$promotion->id}}</td>
			<td>{{$promotion->code}}</td>
			<td>{{$promotion->discount_percentage}}</td>
			<td>{{$promotion->expiry_date}}</td>
			<td>{{$promotion->promotion_status_id}}</td>
			<td>{{$promotion->created_at}}</td>

			<td>
			<form action = "{{route('promotions.destroy',$promotion->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('promotions.show',$promotion->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('promotions.edit',$promotion->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
