<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/promotion/_show.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:33:15
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Promotion')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('promotions.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$promotion->id}}</td></tr>
		<tr><th>Code</th><td>{{$promotion->code}}</td></tr>
		<tr><th>Discount Percentage</th><td>{{$promotion->discount_percentage}}</td></tr>
		<tr><th>Expiry Date</th><td>{{$promotion->expiry_date}}</td></tr>
		<tr><th>Promotion Status Id</th><td>{{$promotion->promotion_status_id}}</td></tr>
		<tr><th>Created At</th><td>{{$promotion->created_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
