<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/product/_create.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:05:08
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Product')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('products.index')}}">Manage</a>
<form action="{{route('products.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="description" class="col-sm-2 col-form-label">Description</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="description" id="description" placeholder="Description"></textarea>
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" id="price" placeholder="Price">
	</div>
</div>
<div class="row mb-3">
	<label for="category_id" class="col-sm-2 col-form-label">Category</label>
	<div class="col-sm-10">
		<select class="form-control" name="category_id" id="category_id">
			@foreach($categories as $category)
				<option value="{{$category->id}}">{{$category->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="brand_id" class="col-sm-2 col-form-label">Brand</label>
	<div class="col-sm-10">
		<select class="form-control" name="brand_id" id="brand_id">
			@foreach($brands as $brand)
				<option value="{{$brand->id}}">{{$brand->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="color_id" class="col-sm-2 col-form-label">Color Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="color_id" id="color_id" placeholder="Color Id">
	</div>
</div>
<div class="row mb-3">
	<label for="size_id" class="col-sm-2 col-form-label">Size Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="size_id" id="size_id" placeholder="Size Id">
	</div>
</div>
<div class="row mb-3">
	<label for="product_image_id" class="col-sm-2 col-form-label">Product_Image</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_image_id" id="product_image_id">
			@foreach($product_images as $product_image)
				<option value="{{$product_image->id}}">{{$product_image->name}}</option>
			@endforeach
		</select>
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
