<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/product/_show.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:05:08
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Product')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('products.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$product->id}}</td></tr>
		<tr><th>Name</th><td>{{$product->name}}</td></tr>
		<tr><th>Description</th><td>{{$product->description}}</td></tr>
		<tr><th>Price</th><td>{{$product->price}}</td></tr>
		<tr><th>Category Id</th><td>{{$product->category_id}}</td></tr>
		<tr><th>Brand Id</th><td>{{$product->brand_id}}</td></tr>
		<tr><th>Color Id</th><td>{{$product->color_id}}</td></tr>
		<tr><th>Size Id</th><td>{{$product->size_id}}</td></tr>
		<tr><th>Product Image Id</th><td>{{$product->product_image_id}}</td></tr>
		<tr><th>Created At</th><td>{{$product->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$product->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
