<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/orderdetail/_create.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:31:46
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create OrderDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('orderdetails.index')}}">Manage</a>
<form action="{{route('orderdetails.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="order_id" class="col-sm-2 col-form-label">Order</label>
	<div class="col-sm-10">
		<select class="form-control" name="order_id" id="order_id">
			@foreach($orders as $order)
				<option value="{{$order->id}}">{{$order->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="product_id" class="col-sm-2 col-form-label">Product</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_id" id="product_id">
			@foreach($products as $product)
				<option value="{{$product->id}}">{{$product->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="quantity" class="col-sm-2 col-form-label">Quantity</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="quantity" id="quantity" placeholder="Quantity">
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" id="price" placeholder="Price">
	</div>
</div>
<div class="row mb-3">
	<label for="discount" class="col-sm-2 col-form-label">Discount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="discount" id="discount" placeholder="Discount">
	</div>
</div>
<div class="row mb-3">
	<label for="subtotal" class="col-sm-2 col-form-label">Subtotal</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="subtotal" id="subtotal" placeholder="Subtotal">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
