<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/orderdetail/_edit.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:31:46
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit OrderDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('orderdetails.index')}}">Manage</a>
<form action="{{route('orderdetails.update',$orderdetail)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="order_id" class="col-sm-2 col-form-label">Order</label>
	<div class="col-sm-10">
		<select class="form-control" name="order_id" id="order_id">
			@foreach($orders as $order)
				@if($order->id==$orderdetail->order_id)
					<option value="{{$order->id}}" selected>{{$order->name}}</option>
				@else
					<option value="{{$order->id}}">{{$order->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="product_id" class="col-sm-2 col-form-label">Product</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_id" id="product_id">
			@foreach($products as $product)
				@if($product->id==$orderdetail->product_id)
					<option value="{{$product->id}}" selected>{{$product->name}}</option>
				@else
					<option value="{{$product->id}}">{{$product->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="quantity" class="col-sm-2 col-form-label">Quantity</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="quantity" value="{{$orderdetail->quantity}}" id="quantity" placeholder="Quantity">
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" value="{{$orderdetail->price}}" id="price" placeholder="Price">
	</div>
</div>
<div class="row mb-3">
	<label for="discount" class="col-sm-2 col-form-label">Discount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="discount" value="{{$orderdetail->discount}}" id="discount" placeholder="Discount">
	</div>
</div>
<div class="row mb-3">
	<label for="subtotal" class="col-sm-2 col-form-label">Subtotal</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="subtotal" value="{{$orderdetail->subtotal}}" id="subtotal" placeholder="Subtotal">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
