<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/stock/_create.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:05:41
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Stock')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('stocks.index')}}">Manage</a>
<form action="{{route('stocks.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="product_id" class="col-sm-2 col-form-label">Product</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_id" id="product_id">
			@foreach($products as $product)
				<option value="{{$product->id}}">{{$product->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="transaction_type" class="col-sm-2 col-form-label">Transaction Type</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="transaction_type" id="transaction_type" placeholder="Transaction Type">
	</div>
</div>
<div class="row mb-3">
	<label for="quantity" class="col-sm-2 col-form-label">Quantity</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="quantity" id="quantity" placeholder="Quantity">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
