<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/stock/_index.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:05:41
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Stock')
@section('style')


@endsection
@section('page')
<a class="btn btn-primary mb-1" href="{{route('stocks.create')}}">New Stock</a>
<table class="table table-hover text-nowrap">
	<thead class="table-dark">
		<tr>

			<th>Product Id</th>
			<th>name</th>
			<th>Quantity</th>
		</tr>
	</thead>
	<tbody>
	@foreach($stocks as $stock)
		<tr>

			<td>{{$stock->product_id}}</td>
			<td>{{$stock->product->name??""}}</td>
			<td>{{$stock->total_qty}}</td>


		</tr>
	@endforeach
	</tbody>
</table>
<div class="d-flex justify-content-center">
    {{ $stocks->links() }}
</div>
@endsection
@section('script')


@endsection
