<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/stock/_show.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:05:41
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Stock')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('stocks.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$stock->id}}</td></tr>
		<tr><th>Product Id</th><td>{{$stock->product_id}}</td></tr>
		<tr><th>Transaction Type</th><td>{{$stock->transaction_type}}</td></tr>
		<tr><th>Quantity</th><td>{{$stock->quantity}}</td></tr>
		<tr><th>Updated At</th><td>{{$stock->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
