<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/contact/_create.blade.php" was generated by ProBot AI.
* Date: 19/03/2025 09:43:45
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Contact')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('contacts.index')}}">Manage</a>
<form action="{{route('contacts.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="email" class="col-sm-2 col-form-label">Email</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="email" id="email" placeholder="Email">
	</div>
</div>
<div class="row mb-3">
	<label for="message" class="col-sm-2 col-form-label">Message</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="message" id="message" placeholder="Message"></textarea>
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
