<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/contact/_index.blade.php" was generated by ProBot AI.
* Date: 19/03/2025 09:43:45
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Contact')
@section('style')


@endsection
@section('page')
<a class="btn btn-primary mb-1" href="{{route('contacts.create')}}">New Contact</a>
<table class="table table-hover text-nowrap">
	<thead class="table-dark">
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Email</th>
			<th>Message</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($contacts as $contact)
		<tr>
			<td>{{$contact->id}}</td>
			<td>{{$contact->name}}</td>
			<td>{{$contact->email}}</td>
			<td>{{$contact->message}}</td>
			<td>{{$contact->created_at}}</td>
			<td>{{$contact->updated_at}}</td>

			<td>
			<form action = "{{route('contacts.destroy',$contact->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('contacts.show',$contact->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('contacts.edit',$contact->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
<div class="d-flex justify-content-center">
    {{ $contacts->links() }}
</div>
@endsection
@section('script')


@endsection
