<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/contact/_show.blade.php" was generated by ProBot AI.
* Date: 19/03/2025 09:43:45
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Contact')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('contacts.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$contact->id}}</td></tr>
		<tr><th>Name</th><td>{{$contact->name}}</td></tr>
		<tr><th>Email</th><td>{{$contact->email}}</td></tr>
		<tr><th>Message</th><td>{{$contact->message}}</td></tr>
		<tr><th>Created At</th><td>{{$contact->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$contact->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
