<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/adjustmenttype/_index.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:27:31
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage AdjustmentType')
@section('style')


@endsection
@section('page')
<a href="{{route('adjustmenttypes.create')}}">New AdjustmentType</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Created At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($adjustmenttypes as $adjustmenttype)
		<tr>
			<td>{{$adjustmenttype->id}}</td>
			<td>{{$adjustmenttype->name}}</td>
			<td>{{$adjustmenttype->created_at}}</td>

			<td>
			<form action = "{{route('adjustmenttypes.destroy',$adjustmenttype->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('adjustmenttypes.show',$adjustmenttype->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('adjustmenttypes.edit',$adjustmenttype->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
