<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/shippingstatu/_index.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:34:59
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage ShippingStatu')
@section('style')


@endsection
@section('page')
<a href="{{route('shippingstatus.create')}}">New ShippingStatu</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Created At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($shippingstatus as $shippingstatu)
		<tr>
			<td>{{$shippingstatu->id}}</td>
			<td>{{$shippingstatu->name}}</td>
			<td>{{$shippingstatu->created_at}}</td>

			<td>
			<form action = "{{route('shippingstatus.destroy',$shippingstatu->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('shippingstatus.show',$shippingstatu->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('shippingstatus.edit',$shippingstatu->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
