<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchase/_index.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:07:29
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Purchase')
@section('style')


@endsection
@section('page')
<a href="{{route('purchases.create')}}">New Purchase</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Supplier Id</th>
			<th>Total Amount</th>
			<th>Purchase Date</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($purchases as $purchase)
		<tr>
			<td>{{$purchase->id}}</td>
			<td>{{$purchase->supplier_id}}</td>
			<td>{{$purchase->total_amount}}</td>
			<td>{{$purchase->purchase_date}}</td>
			<td>{{$purchase->created_at}}</td>
			<td>{{$purchase->updated_at}}</td>

			<td>
			<form action = "{{route('purchases.destroy',$purchase->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('purchases.show',$purchase->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('purchases.edit',$purchase->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
