<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchase/_show.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:07:29
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Purchase')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('purchases.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$purchase->id}}</td></tr>
		<tr><th>Supplier Id</th><td>{{$purchase->supplier_id}}</td></tr>
		<tr><th>Total Amount</th><td>{{$purchase->total_amount}}</td></tr>
		<tr><th>Purchase Date</th><td>{{$purchase->purchase_date}}</td></tr>
		<tr><th>Created At</th><td>{{$purchase->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$purchase->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
