<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/color/_index.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:30:57
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Color')
@section('style')


@endsection
@section('page')
<a href="{{route('colors.create')}}">New Color</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Created At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($colors as $color)
		<tr>
			<td>{{$color->id}}</td>
			<td>{{$color->name}}</td>
			<td>{{$color->created_at}}</td>

			<td>
			<form action = "{{route('colors.destroy',$color->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('colors.show',$color->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('colors.edit',$color->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
