<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/color/_show.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:30:57
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Color')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('colors.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$color->id}}</td></tr>
		<tr><th>Name</th><td>{{$color->name}}</td></tr>
		<tr><th>Created At</th><td>{{$color->created_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
