<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/user/_edit.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:06:01
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit User')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('users.index')}}">Manage</a>
<form action="{{route('users.update',$user)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$user->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="role_id" class="col-sm-2 col-form-label">Role</label>
	<div class="col-sm-10">
		<select class="form-control" name="role_id" id="role_id">
			@foreach($roles as $role)
				@if($role->id==$user->role_id)
					<option value="{{$role->id}}" selected>{{$role->name}}</option>
				@else
					<option value="{{$role->id}}">{{$role->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="password" class="col-sm-2 col-form-label">Password</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="password" value="{{$user->password}}" id="password" placeholder="Password">
	</div>
</div>
<div class="row mb-3">
	<label for="email" class="col-sm-2 col-form-label">Email</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="email" value="{{$user->email}}" id="email" placeholder="Email">
	</div>
</div>
<div class="row mb-3">
	<label for="full_name" class="col-sm-2 col-form-label">Full Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="full_name" value="{{$user->full_name}}" id="full_name" placeholder="Full Name">
	</div>
</div>
<div class="row mb-3">
	<label for="photo" class="col-sm-2 col-form-label">Photo</label>
	<div class="col-sm-10">
		<input type = "file" class="form-control" name="photo"  id="photo" placeholder="Photo">
	</div>
</div>
<div class="row mb-3">
	<label for="verify_code" class="col-sm-2 col-form-label">Verify Code</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="verify_code" value="{{$user->verify_code}}" id="verify_code" placeholder="Verify Code">
	</div>
</div>
<div class="row mb-3">
	<label for="mobile" class="col-sm-2 col-form-label">Mobile</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="mobile" value="{{$user->mobile}}" id="mobile" placeholder="Mobile">
	</div>
</div>
<div class="row mb-3">
	<label for="ip" class="col-sm-2 col-form-label">Ip</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="ip" value="{{$user->ip}}" id="ip" placeholder="Ip">
	</div>
</div>
<div class="row mb-3">
	<label for="remember_token" class="col-sm-2 col-form-label">Remember Token</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="remember_token" value="{{$user->remember_token}}" id="remember_token" placeholder="Remember Token">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
