<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/user/_index.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:06:01
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage User')
@section('style')


@endsection
@section('page')
<a href="{{route('users.create')}}">New User</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Role Id</th>
			<th>Password</th>
			<th>Email</th>
			<th>Full Name</th>
			<th>Created At</th>
			<th>Photo</th>
			<th>Verify Code</th>
			<th>Inactive</th>
			<th>Mobile</th>
			<th>Updated At</th>
			<th>Ip</th>
			<th>Email Verified At</th>
			<th>Remember Token</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($users as $user)
		<tr>
			<td>{{$user->id}}</td>
			<td>{{$user->name}}</td>
			<td>{{$user->role_id}}</td>
			<td>{{$user->password}}</td>
			<td>{{$user->email}}</td>
			<td>{{$user->full_name}}</td>
			<td>{{$user->created_at}}</td>
			<td><img src="{{asset('img/'.$user->photo)}}" width="100" /></td>
			<td>{{$user->verify_code}}</td>
			<td>{{$user->inactive}}</td>
			<td>{{$user->mobile}}</td>
			<td>{{$user->updated_at}}</td>
			<td>{{$user->ip}}</td>
			<td>{{$user->email_verified_at}}</td>
			<td>{{$user->remember_token}}</td>

			<td>
			<form action = "{{route('users.destroy',$user->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('users.show',$user->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('users.edit',$user->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
