<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/user/_show.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:06:01
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show User')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('users.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$user->id}}</td></tr>
		<tr><th>Name</th><td>{{$user->name}}</td></tr>
		<tr><th>Role Id</th><td>{{$user->role_id}}</td></tr>
		<tr><th>Password</th><td>{{$user->password}}</td></tr>
		<tr><th>Email</th><td>{{$user->email}}</td></tr>
		<tr><th>Full Name</th><td>{{$user->full_name}}</td></tr>
		<tr><th>Created At</th><td>{{$user->created_at}}</td></tr>
		<tr><th>Photo</th><td><img src="{{asset('img/'.$user->photo)}}" width="100" /></td></tr>
		<tr><th>Verify Code</th><td>{{$user->verify_code}}</td></tr>
		<tr><th>Inactive</th><td>{{$user->inactive}}</td></tr>
		<tr><th>Mobile</th><td>{{$user->mobile}}</td></tr>
		<tr><th>Updated At</th><td>{{$user->updated_at}}</td></tr>
		<tr><th>Ip</th><td>{{$user->ip}}</td></tr>
		<tr><th>Email Verified At</th><td>{{$user->email_verified_at}}</td></tr>
		<tr><th>Remember Token</th><td>{{$user->remember_token}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
