<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/productimage/_edit.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:32:46
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit ProductImage')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('productimages.index')}}">Manage</a>
<form action="{{route('productimages.update',$productimage)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="product_id" class="col-sm-2 col-form-label">Product</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_id" id="product_id">
			@foreach($products as $product)
				@if($product->id==$productimage->product_id)
					<option value="{{$product->id}}" selected>{{$product->name}}</option>
				@else
					<option value="{{$product->id}}">{{$product->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="image_name" class="col-sm-2 col-form-label">Image Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="image_name" value="{{$productimage->image_name}}" id="image_name" placeholder="Image Name">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
