<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/productimage/_index.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:32:46
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage ProductImage')
@section('style')


@endsection
@section('page')
<a href="{{route('productimages.create')}}">New ProductImage</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Product Id</th>
			<th>Image Name</th>
			<th>Is Primary</th>
			<th>Created At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($productimages as $productimage)
		<tr>
			<td>{{$productimage->id}}</td>
			<td>{{$productimage->product_id}}</td>
			<td>{{$productimage->image_name}}</td>
			<td>{{$productimage->is_primary}}</td>
			<td>{{$productimage->created_at}}</td>

			<td>
			<form action = "{{route('productimages.destroy',$productimage->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('productimages.show',$productimage->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('productimages.edit',$productimage->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
