<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/productimage/_show.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:32:46
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show ProductImage')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('productimages.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$productimage->id}}</td></tr>
		<tr><th>Product Id</th><td>{{$productimage->product_id}}</td></tr>
		<tr><th>Image Name</th><td>{{$productimage->image_name}}</td></tr>
		<tr><th>Is Primary</th><td>{{$productimage->is_primary}}</td></tr>
		<tr><th>Created At</th><td>{{$productimage->created_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
