<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/orderstatu/_index.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:32:18
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage OrderStatu')
@section('style')


@endsection
@section('page')
<a href="{{route('orderstatus.create')}}">New OrderStatu</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($orderstatus as $orderstatu)
		<tr>
			<td>{{$orderstatu->id}}</td>
			<td>{{$orderstatu->name}}</td>
			<td>{{$orderstatu->created_at}}</td>
			<td>{{$orderstatu->updated_at}}</td>

			<td>
			<form action = "{{route('orderstatus.destroy',$orderstatu->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('orderstatus.show',$orderstatu->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('orderstatus.edit',$orderstatu->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
