<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/category/_edit.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:06:41
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Category')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('categorys.index')}}">Manage</a>
<form action="{{route('categorys.update',$category)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$category->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="parent_id" class="col-sm-2 col-form-label">Parent</label>
	<div class="col-sm-10">
		<select class="form-control" name="parent_id" id="parent_id">
			@foreach($parents as $parent)
				@if($parent->id==$category->parent_id)
					<option value="{{$parent->id}}" selected>{{$parent->name}}</option>
				@else
					<option value="{{$parent->id}}">{{$parent->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
