<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/category/_show.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:06:41
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Category')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('categorys.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$category->id}}</td></tr>
		<tr><th>Name</th><td>{{$category->name}}</td></tr>
		<tr><th>Parent Id</th><td>{{$category->parent_id}}</td></tr>
		<tr><th>Created At</th><td>{{$category->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$category->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
