<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/review/_create.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:07:46
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Review')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('reviews.index')}}">Manage</a>
<form action="{{route('reviews.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="customer_id" class="col-sm-2 col-form-label">Customer</label>
	<div class="col-sm-10">
		<select class="form-control" name="customer_id" id="customer_id">
			@foreach($customers as $customer)
				<option value="{{$customer->id}}">{{$customer->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="product_id" class="col-sm-2 col-form-label">Product</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_id" id="product_id">
			@foreach($products as $product)
				<option value="{{$product->id}}">{{$product->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="rating" class="col-sm-2 col-form-label">Rating</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="rating" id="rating" placeholder="Rating">
	</div>
</div>
<div class="row mb-3">
	<label for="comment" class="col-sm-2 col-form-label">Comment</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="comment" id="comment" placeholder="Comment"></textarea>
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
