<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/review/_index.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:07:46
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Review')
@section('style')


@endsection
@section('page')
<a href="{{route('reviews.create')}}">New Review</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Customer Id</th>
			<th>Product Id</th>
			<th>Rating</th>
			<th>Comment</th>
			<th>Created At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($reviews as $review)
		<tr>
			<td>{{$review->id}}</td>
			<td>{{$review->customer_id}}</td>
			<td>{{$review->product_id}}</td>
			<td>{{$review->rating}}</td>
			<td>{{$review->comment}}</td>
			<td>{{$review->created_at}}</td>

			<td>
			<form action = "{{route('reviews.destroy',$review->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('reviews.show',$review->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('reviews.edit',$review->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
