<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/review/_show.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:07:46
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Review')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('reviews.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$review->id}}</td></tr>
		<tr><th>Customer Id</th><td>{{$review->customer_id}}</td></tr>
		<tr><th>Product Id</th><td>{{$review->product_id}}</td></tr>
		<tr><th>Rating</th><td>{{$review->rating}}</td></tr>
		<tr><th>Comment</th><td>{{$review->comment}}</td></tr>
		<tr><th>Created At</th><td>{{$review->created_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
