<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_AdjustmentTypeController.php" was generated by ProBot AI.
* Date: 25/02/2025 13:27:09
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\AdjustmentType;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class AdjustmentTypeController extends Controller{
	public function index(){
		$adjustmenttypes = AdjustmentType::paginate(10);
		return view("pages.erp.adjustmenttype.index",["adjustmenttypes"=>$adjustmenttypes]);
	}
	public function create(){
		return view("pages.erp.adjustmenttype.create",[]);
	}
	public function store(Request $request){
		//AdjustmentType::create($request->all());
		$adjustmenttype = new AdjustmentType;
		$adjustmenttype->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$adjustmenttype->created_at=date('Y-m-d H:i:s');

		$adjustmenttype->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$adjustmenttype = AdjustmentType::find($id);
		return view("pages.erp.adjustmenttype.show",["adjustmenttype"=>$adjustmenttype]);
	}
	public function edit(AdjustmentType $adjustmenttype){
		return view("pages.erp.adjustmenttype.edit",["adjustmenttype"=>$adjustmenttype,]);
	}
	public function update(Request $request,AdjustmentType $adjustmenttype){
		//AdjustmentType::update($request->all());
		$adjustmenttype = AdjustmentType::find($adjustmenttype->id);
		$adjustmenttype->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$adjustmenttype->created_at=date('Y-m-d H:i:s');

		$adjustmenttype->save();

		return redirect()->route("adjustmenttypes.index")->with('success','Updated Successfully.');
	}
	public function destroy(AdjustmentType $adjustmenttype){
		$adjustmenttype->delete();
		return redirect()->route("adjustmenttypes.index")->with('success', 'Deleted Successfully.');
	}
}
?>
