<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_BrandController.php" was generated by ProBot AI.
* Date: 25/02/2025 13:29:10
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Brand;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class BrandController extends Controller{
	public function index(){
		$brands = Brand::paginate(10);
		return view("pages.erp.brand.index",["brands"=>$brands]);
	}
	public function create(){
		return view("pages.erp.brand.create",[]);
	}
	public function store(Request $request){
		//Brand::create($request->all());
		$brand = new Brand;
		$brand->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$brand->created_at=date('Y-m-d H:i:s');

		$brand->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$brand = Brand::find($id);
		return view("pages.erp.brand.show",["brand"=>$brand]);
	}
	public function edit(Brand $brand){
		return view("pages.erp.brand.edit",["brand"=>$brand,]);
	}
	public function update(Request $request,Brand $brand){
		//Brand::update($request->all());
		$brand = Brand::find($brand->id);
		$brand->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$brand->created_at=date('Y-m-d H:i:s');

		$brand->save();

		return redirect()->route("brands.index")->with('success','Updated Successfully.');
	}
	public function destroy(Brand $brand){
		$brand->delete();
		return redirect()->route("brands.index")->with('success', 'Deleted Successfully.');
	}
}
?>
