<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ColorController.php" was generated by ProBot AI.
* Date: 25/02/2025 13:30:52
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Color;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ColorController extends Controller{
	public function index(){
		$colors = Color::paginate(10);
		return view("pages.erp.color.index",["colors"=>$colors]);
	}
	public function create(){
		return view("pages.erp.color.create",[]);
	}
	public function store(Request $request){
		//Color::create($request->all());
		$color = new Color;
		$color->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$color->created_at=date('Y-m-d H:i:s');

		$color->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$color = Color::find($id);
		return view("pages.erp.color.show",["color"=>$color]);
	}
	public function edit(Color $color){
		return view("pages.erp.color.edit",["color"=>$color,]);
	}
	public function update(Request $request,Color $color){
		//Color::update($request->all());
		$color = Color::find($color->id);
		$color->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$color->created_at=date('Y-m-d H:i:s');

		$color->save();

		return redirect()->route("colors.index")->with('success','Updated Successfully.');
	}
	public function destroy(Color $color){
		$color->delete();
		return redirect()->route("colors.index")->with('success', 'Deleted Successfully.');
	}
}
?>
