<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_OrderController.php" was generated by ProBot AI.
* Date: 24/02/2025 14:06:52
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\Customer;
use App\Models\Order_Status;
use App\Models\Payment_Status;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class OrderController extends Controller{
	public function index(){
		$orders = Order::paginate(10);
		return view("pages.erp.order.index",["orders"=>$orders]);
	}
	public function create(){
		return view("pages.erp.order.create",["customers"=>Customer::all(),"order_statuss"=>Order_Status::all(),"payment_statuss"=>Payment_Status::all()]);
	}
	public function store(Request $request){
		//Order::create($request->all());
		$order = new Order;
		$order->customer_id=$request->customer_id;
		$order->total_price=$request->total_price;
		$order->order_status_id=$request->order_status_id;
		$order->payment_status_id=$request->payment_status_id;
date_default_timezone_set("Asia/Dhaka");
		$order->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$order->updated_at=date('Y-m-d H:i:s');

		$order->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$order = Order::find($id);
		return view("pages.erp.order.show",["order"=>$order]);
	}
	public function edit(Order $order){
		return view("pages.erp.order.edit",["order"=>$order,"customers"=>Customer::all(),"order_statuss"=>Order_Status::all(),"payment_statuss"=>Payment_Status::all()]);
	}
	public function update(Request $request,Order $order){
		//Order::update($request->all());
		$order = Order::find($order->id);
		$order->customer_id=$request->customer_id;
		$order->total_price=$request->total_price;
		$order->order_status_id=$request->order_status_id;
		$order->payment_status_id=$request->payment_status_id;
date_default_timezone_set("Asia/Dhaka");
		$order->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$order->updated_at=date('Y-m-d H:i:s');

		$order->save();

		return redirect()->route("orders.index")->with('success','Updated Successfully.');
	}
	public function destroy(Order $order){
		$order->delete();
		return redirect()->route("orders.index")->with('success', 'Deleted Successfully.');
	}
}
?>
