<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_OrderStatuController.php" was generated by ProBot AI.
* Date: 25/02/2025 13:32:12
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\OrderStatu;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class OrderStatuController extends Controller{
	public function index(){
		$orderstatus = OrderStatu::paginate(10);
		return view("pages.erp.orderstatu.index",["orderstatus"=>$orderstatus]);
	}
	public function create(){
		return view("pages.erp.orderstatu.create",[]);
	}
	public function store(Request $request){
		//OrderStatu::create($request->all());
		$orderstatu = new OrderStatu;
		$orderstatu->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$orderstatu->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$orderstatu->updated_at=date('Y-m-d H:i:s');

		$orderstatu->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$orderstatu = OrderStatu::find($id);
		return view("pages.erp.orderstatu.show",["orderstatu"=>$orderstatu]);
	}
	public function edit(OrderStatu $orderstatu){
		return view("pages.erp.orderstatu.edit",["orderstatu"=>$orderstatu,]);
	}
	public function update(Request $request,OrderStatu $orderstatu){
		//OrderStatu::update($request->all());
		$orderstatu = OrderStatu::find($orderstatu->id);
		$orderstatu->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$orderstatu->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$orderstatu->updated_at=date('Y-m-d H:i:s');

		$orderstatu->save();

		return redirect()->route("orderstatus.index")->with('success','Updated Successfully.');
	}
	public function destroy(OrderStatu $orderstatu){
		$orderstatu->delete();
		return redirect()->route("orderstatus.index")->with('success', 'Deleted Successfully.');
	}
}
?>
