<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ProductImageController.php" was generated by ProBot AI.
* Date: 25/02/2025 13:32:43
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\ProductImage;
use App\Models\Product;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ProductImageController extends Controller{
	public function index(){
		$productimages = ProductImage::paginate(10);
		return view("pages.erp.productimage.index",["productimages"=>$productimages]);
	}
	public function create(){
		return view("pages.erp.productimage.create",["products"=>Product::all()]);
	}
	public function store(Request $request){
		//ProductImage::create($request->all());
		$productimage = new ProductImage;
		$productimage->product_id=$request->product_id;
		$productimage->image_name=$request->image_name;
		$productimage->is_primary=$request->is_primary;
date_default_timezone_set("Asia/Dhaka");
		$productimage->created_at=date('Y-m-d H:i:s');

		$productimage->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$productimage = ProductImage::find($id);
		return view("pages.erp.productimage.show",["productimage"=>$productimage]);
	}
	public function edit(ProductImage $productimage){
		return view("pages.erp.productimage.edit",["productimage"=>$productimage,"products"=>Product::all()]);
	}
	public function update(Request $request,ProductImage $productimage){
		//ProductImage::update($request->all());
		$productimage = ProductImage::find($productimage->id);
		$productimage->product_id=$request->product_id;
		$productimage->image_name=$request->image_name;
		$productimage->is_primary=$request->is_primary;
date_default_timezone_set("Asia/Dhaka");
		$productimage->created_at=date('Y-m-d H:i:s');

		$productimage->save();

		return redirect()->route("productimages.index")->with('success','Updated Successfully.');
	}
	public function destroy(ProductImage $productimage){
		$productimage->delete();
		return redirect()->route("productimages.index")->with('success', 'Deleted Successfully.');
	}
}
?>
