<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PromotionController.php" was generated by ProBot AI.
* Date: 25/02/2025 13:33:13
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Promotion;
use App\Models\Promotion_Status;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PromotionController extends Controller{
	public function index(){
		$promotions = Promotion::paginate(10);
		return view("pages.erp.promotion.index",["promotions"=>$promotions]);
	}
	public function create(){
		return view("pages.erp.promotion.create",["promotion_statuss"=>Promotion_Status::all()]);
	}
	public function store(Request $request){
		//Promotion::create($request->all());
		$promotion = new Promotion;
		$promotion->code=$request->code;
		$promotion->discount_percentage=$request->discount_percentage;
		$promotion->expiry_date=$request->expiry_date;
		$promotion->promotion_status_id=$request->promotion_status_id;
date_default_timezone_set("Asia/Dhaka");
		$promotion->created_at=date('Y-m-d H:i:s');

		$promotion->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$promotion = Promotion::find($id);
		return view("pages.erp.promotion.show",["promotion"=>$promotion]);
	}
	public function edit(Promotion $promotion){
		return view("pages.erp.promotion.edit",["promotion"=>$promotion,"promotion_statuss"=>Promotion_Status::all()]);
	}
	public function update(Request $request,Promotion $promotion){
		//Promotion::update($request->all());
		$promotion = Promotion::find($promotion->id);
		$promotion->code=$request->code;
		$promotion->discount_percentage=$request->discount_percentage;
		$promotion->expiry_date=$request->expiry_date;
		$promotion->promotion_status_id=$request->promotion_status_id;
date_default_timezone_set("Asia/Dhaka");
		$promotion->created_at=date('Y-m-d H:i:s');

		$promotion->save();

		return redirect()->route("promotions.index")->with('success','Updated Successfully.');
	}
	public function destroy(Promotion $promotion){
		$promotion->delete();
		return redirect()->route("promotions.index")->with('success', 'Deleted Successfully.');
	}
}
?>
