<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PromotionStatuController.php" was generated by ProBot AI.
* Date: 25/02/2025 13:33:39
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\PromotionStatu;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PromotionStatuController extends Controller{
	public function index(){
		$promotionstatus = PromotionStatu::paginate(10);
		return view("pages.erp.promotionstatu.index",["promotionstatus"=>$promotionstatus]);
	}
	public function create(){
		return view("pages.erp.promotionstatu.create",[]);
	}
	public function store(Request $request){
		//PromotionStatu::create($request->all());
		$promotionstatu = new PromotionStatu;
		$promotionstatu->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$promotionstatu->created_at=date('Y-m-d H:i:s');

		$promotionstatu->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$promotionstatu = PromotionStatu::find($id);
		return view("pages.erp.promotionstatu.show",["promotionstatu"=>$promotionstatu]);
	}
	public function edit(PromotionStatu $promotionstatu){
		return view("pages.erp.promotionstatu.edit",["promotionstatu"=>$promotionstatu,]);
	}
	public function update(Request $request,PromotionStatu $promotionstatu){
		//PromotionStatu::update($request->all());
		$promotionstatu = PromotionStatu::find($promotionstatu->id);
		$promotionstatu->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$promotionstatu->created_at=date('Y-m-d H:i:s');

		$promotionstatu->save();

		return redirect()->route("promotionstatus.index")->with('success','Updated Successfully.');
	}
	public function destroy(PromotionStatu $promotionstatu){
		$promotionstatu->delete();
		return redirect()->route("promotionstatus.index")->with('success', 'Deleted Successfully.');
	}
}
?>
