<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ShippingController.php" was generated by ProBot AI.
* Date: 24/02/2025 14:07:16
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Shipping;
use App\Models\Order;
use App\Models\Shipping_Status;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ShippingController extends Controller{
	public function index(){
		$shippings = Shipping::paginate(10);
		return view("pages.erp.shipping.index",["shippings"=>$shippings]);
	}
	public function create(){
		return view("pages.erp.shipping.create",["orders"=>Order::all(),"shipping_statuss"=>Shipping_Status::all()]);
	}
	public function store(Request $request){
		//Shipping::create($request->all());
		$shipping = new Shipping;
		$shipping->order_id=$request->order_id;
		$shipping->tracking_number=$request->tracking_number;
		$shipping->carrier=$request->carrier;
		$shipping->shipping_status_id=$request->shipping_status_id;
		$shipping->estimated_delivery_date=$request->estimated_delivery_date;
date_default_timezone_set("Asia/Dhaka");
		$shipping->created_at=date('Y-m-d H:i:s');

		$shipping->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$shipping = Shipping::find($id);
		return view("pages.erp.shipping.show",["shipping"=>$shipping]);
	}
	public function edit(Shipping $shipping){
		return view("pages.erp.shipping.edit",["shipping"=>$shipping,"orders"=>Order::all(),"shipping_statuss"=>Shipping_Status::all()]);
	}
	public function update(Request $request,Shipping $shipping){
		//Shipping::update($request->all());
		$shipping = Shipping::find($shipping->id);
		$shipping->order_id=$request->order_id;
		$shipping->tracking_number=$request->tracking_number;
		$shipping->carrier=$request->carrier;
		$shipping->shipping_status_id=$request->shipping_status_id;
		$shipping->estimated_delivery_date=$request->estimated_delivery_date;
date_default_timezone_set("Asia/Dhaka");
		$shipping->created_at=date('Y-m-d H:i:s');

		$shipping->save();

		return redirect()->route("shippings.index")->with('success','Updated Successfully.');
	}
	public function destroy(Shipping $shipping){
		$shipping->delete();
		return redirect()->route("shippings.index")->with('success', 'Deleted Successfully.');
	}
}
?>
