<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_SizeController.php" was generated by ProBot AI.
* Date: 25/02/2025 13:35:27
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Size;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class SizeController extends Controller{
	public function index(){
		$sizes = Size::paginate(10);
		return view("pages.erp.size.index",["sizes"=>$sizes]);
	}
	public function create(){
		return view("pages.erp.size.create",[]);
	}
	public function store(Request $request){
		//Size::create($request->all());
		$size = new Size;
		$size->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$size->created_at=date('Y-m-d H:i:s');

		$size->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$size = Size::find($id);
		return view("pages.erp.size.show",["size"=>$size]);
	}
	public function edit(Size $size){
		return view("pages.erp.size.edit",["size"=>$size,]);
	}
	public function update(Request $request,Size $size){
		//Size::update($request->all());
		$size = Size::find($size->id);
		$size->name=$request->name;
date_default_timezone_set("Asia/Dhaka");
		$size->created_at=date('Y-m-d H:i:s');

		$size->save();

		return redirect()->route("sizes.index")->with('success','Updated Successfully.');
	}
	public function destroy(Size $size){
		$size->delete();
		return redirect()->route("sizes.index")->with('success', 'Deleted Successfully.');
	}
}
?>
