<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_WishlistController.php" was generated by ProBot AI.
* Date: 25/02/2025 13:37:28
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Wishlist;
use App\Models\Customer;
use App\Models\Product;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class WishlistController extends Controller{
	public function index(){
		$wishlists = Wishlist::paginate(10);
		return view("pages.erp.wishlist.index",["wishlists"=>$wishlists]);
	}
	public function create(){
		return view("pages.erp.wishlist.create",["customers"=>Customer::all(),"products"=>Product::all()]);
	}
	public function store(Request $request){
		//Wishlist::create($request->all());
		$wishlist = new Wishlist;
		$wishlist->customer_id=$request->customer_id;
		$wishlist->product_id=$request->product_id;
		$wishlist->quantity=$request->quantity;
date_default_timezone_set("Asia/Dhaka");
		$wishlist->created_at=date('Y-m-d H:i:s');

		$wishlist->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$wishlist = Wishlist::find($id);
		return view("pages.erp.wishlist.show",["wishlist"=>$wishlist]);
	}
	public function edit(Wishlist $wishlist){
		return view("pages.erp.wishlist.edit",["wishlist"=>$wishlist,"customers"=>Customer::all(),"products"=>Product::all()]);
	}
	public function update(Request $request,Wishlist $wishlist){
		//Wishlist::update($request->all());
		$wishlist = Wishlist::find($wishlist->id);
		$wishlist->customer_id=$request->customer_id;
		$wishlist->product_id=$request->product_id;
		$wishlist->quantity=$request->quantity;
date_default_timezone_set("Asia/Dhaka");
		$wishlist->created_at=date('Y-m-d H:i:s');

		$wishlist->save();

		return redirect()->route("wishlists.index")->with('success','Updated Successfully.');
	}
	public function destroy(Wishlist $wishlist){
		$wishlist->delete();
		return redirect()->route("wishlists.index")->with('success', 'Deleted Successfully.');
	}
}
?>
