<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/brand/_index.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:29:18
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Brand')
@section('style')


@endsection
@section('page')
<a href="{{route('brands.create')}}">New Brand</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Created At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($brands as $brand)
		<tr>
			<td>{{$brand->id}}</td>
			<td>{{$brand->name}}</td>
			<td>{{$brand->created_at}}</td>

			<td>
			<form action = "{{route('brands.destroy',$brand->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('brands.show',$brand->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('brands.edit',$brand->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
