<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasedetail/_edit.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:34:04
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit PurchaseDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('purchasedetails.index')}}">Manage</a>
<form action="{{route('purchasedetails.update',$purchasedetail)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="purchase_id" class="col-sm-2 col-form-label">Purchase</label>
	<div class="col-sm-10">
		<select class="form-control" name="purchase_id" id="purchase_id">
			@foreach($purchases as $purchase)
				@if($purchase->id==$purchasedetail->purchase_id)
					<option value="{{$purchase->id}}" selected>{{$purchase->name}}</option>
				@else
					<option value="{{$purchase->id}}">{{$purchase->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="product_id" class="col-sm-2 col-form-label">Product</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_id" id="product_id">
			@foreach($products as $product)
				@if($product->id==$purchasedetail->product_id)
					<option value="{{$product->id}}" selected>{{$product->name}}</option>
				@else
					<option value="{{$product->id}}">{{$product->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="quantity" class="col-sm-2 col-form-label">Quantity</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="quantity" value="{{$purchasedetail->quantity}}" id="quantity" placeholder="Quantity">
	</div>
</div>
<div class="row mb-3">
	<label for="cost_price" class="col-sm-2 col-form-label">Cost Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="cost_price" value="{{$purchasedetail->cost_price}}" id="cost_price" placeholder="Cost Price">
	</div>
</div>
<div class="row mb-3">
	<label for="subtotal" class="col-sm-2 col-form-label">Subtotal</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="subtotal" value="{{$purchasedetail->subtotal}}" id="subtotal" placeholder="Subtotal">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
