<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/purchasedetail/_show.blade.php" was generated by ProBot AI.
* Date: 25/02/2025 13:34:04
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show PurchaseDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('purchasedetails.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$purchasedetail->id}}</td></tr>
		<tr><th>Purchase Id</th><td>{{$purchasedetail->purchase_id}}</td></tr>
		<tr><th>Product Id</th><td>{{$purchasedetail->product_id}}</td></tr>
		<tr><th>Quantity</th><td>{{$purchasedetail->quantity}}</td></tr>
		<tr><th>Cost Price</th><td>{{$purchasedetail->cost_price}}</td></tr>
		<tr><th>Subtotal</th><td>{{$purchasedetail->subtotal}}</td></tr>
		<tr><th>Created At</th><td>{{$purchasedetail->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$purchasedetail->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
