<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Contact.php" was generated by ProBot AI.
* Date: 19/03/2025 09:43:45
* Contact: towhid1@outlook.com
*/
// namespace App\Models;
// use Illuminate\Database\Eloquent\Model;
// class ContactA extends Model{


// }
// ?>
