<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_AdjustmentType.php" was generated by ProBot AI.
* Date: 25/02/2025 13:27:31
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class AdjustmentType extends Model{


}
?>
