<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Contact.php" was generated by ProBot AI.
* Date: 17/03/2025 13:01:23
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Contact extends Model{


}
?>
