<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_OrderDetail.php" was generated by ProBot AI.
* Date: 25/02/2025 13:31:46
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class OrderDetail extends Model{


}
?>
