<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Payment.php" was generated by ProBot AI.
* Date: 24/02/2025 14:07:39
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Payment extends Model{


}
?>
