<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Product.php" was generated by ProBot AI.
* Date: 24/02/2025 14:05:08
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Product extends Model{


}
?>
