<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_PurchaseDetail.php" was generated by ProBot AI.
* Date: 25/02/2025 13:34:04
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class PurchaseDetail extends Model{


}
?>
