<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Size.php" was generated by ProBot AI.
* Date: 25/02/2025 13:35:29
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Size extends Model{


}
?>
