<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/shipping/_create.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:07:16
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Shipping')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('shippings.index')}}">Manage</a>
<form action="{{route('shippings.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="order_id" class="col-sm-2 col-form-label">Order</label>
	<div class="col-sm-10">
		<select class="form-control" name="order_id" id="order_id">
			@foreach($orders as $order)
				<option value="{{$order->id}}">{{$order->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="tracking_number" class="col-sm-2 col-form-label">Tracking Number</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="tracking_number" id="tracking_number" placeholder="Tracking Number">
	</div>
</div>
<div class="row mb-3">
	<label for="carrier" class="col-sm-2 col-form-label">Carrier</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="carrier" id="carrier" placeholder="Carrier">
	</div>
</div>
<div class="row mb-3">
	<label for="shipping_status_id" class="col-sm-2 col-form-label">Shipping_Status</label>
	<div class="col-sm-10">
		<select class="form-control" name="shipping_status_id" id="shipping_status_id">
			@foreach($shipping_statuss as $shipping_status)
				<option value="{{$shipping_status->id}}">{{$shipping_status->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="estimated_delivery_date" class="col-sm-2 col-form-label">Estimated Delivery Date</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="estimated_delivery_date" id="estimated_delivery_date" placeholder="Estimated Delivery Date">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
