<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/shipping/_index.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:07:16
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Shipping')
@section('style')


@endsection
@section('page')
<a href="{{route('shippings.create')}}">New Shipping</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Order Id</th>
			<th>Tracking Number</th>
			<th>Carrier</th>
			<th>Shipping Status Id</th>
			<th>Estimated Delivery Date</th>
			<th>Created At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($shippings as $shipping)
		<tr>
			<td>{{$shipping->id}}</td>
			<td>{{$shipping->order_id}}</td>
			<td>{{$shipping->tracking_number}}</td>
			<td>{{$shipping->carrier}}</td>
			<td>{{$shipping->shipping_status_id}}</td>
			<td>{{$shipping->estimated_delivery_date}}</td>
			<td>{{$shipping->created_at}}</td>

			<td>
			<form action = "{{route('shippings.destroy',$shipping->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('shippings.show',$shipping->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('shippings.edit',$shipping->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
