<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/shipping/_show.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:07:16
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Shipping')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('shippings.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$shipping->id}}</td></tr>
		<tr><th>Order Id</th><td>{{$shipping->order_id}}</td></tr>
		<tr><th>Tracking Number</th><td>{{$shipping->tracking_number}}</td></tr>
		<tr><th>Carrier</th><td>{{$shipping->carrier}}</td></tr>
		<tr><th>Shipping Status Id</th><td>{{$shipping->shipping_status_id}}</td></tr>
		<tr><th>Estimated Delivery Date</th><td>{{$shipping->estimated_delivery_date}}</td></tr>
		<tr><th>Created At</th><td>{{$shipping->created_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
