<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/payment/_show.blade.php" was generated by ProBot AI.
* Date: 24/02/2025 14:07:39
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Payment')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('payments.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$payment->id}}</td></tr>
		<tr><th>Order Id</th><td>{{$payment->order_id}}</td></tr>
		<tr><th>Customer Id</th><td>{{$payment->customer_id}}</td></tr>
		<tr><th>Amount</th><td>{{$payment->amount}}</td></tr>
		<tr><th>Payment Method Id</th><td>{{$payment->payment_method_id}}</td></tr>
		<tr><th>Transaction Id</th><td>{{$payment->transaction_id}}</td></tr>
		<tr><th>Created At</th><td>{{$payment->created_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
